language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

cache: pip

install:
  - python setup.py build
  - python setup.py install
  - pip install pytest-cov requests-mock

script:
  - py.test

after_success:
  - codecov
